name: Lint

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
  workflow_dispatch:

jobs:
  black:
    name: Black (py39 style)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip setuptools
          pip install black==22.8.0

      - name: Black (diff)
        run: black --diff -S -t py39 protein_tune_rl

      - name: Black (check)
        run: black --check -S -t py39 protein_tune_rl

  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    needs: black
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip setuptools
          pip install flake8==5.0.4

      - name: Run flake8
        run: flake8 --ignore E501,E203,W503 protein_tune_rl
